# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for Roam. Build with:  pyinstaller roam.spec
# Produces a one-folder Windows application under dist/Roam/ (dist/Roam/Roam.exe).
#
# Data files are bundled at the same relative paths the game already uses
# ("assets/...", "schemas/...", "config.yml"); src/appPaths.prepareWorkingDirectory()
# chdir's into the bundle at startup so those relative paths resolve when frozen.
import os

# icon.ico is generated by install.ps1 (and gitignored); only set it if present
# so a from-source build without it still succeeds.
iconPath = os.path.join("src", "media", "icon.ico")
icon = iconPath if os.path.exists(iconPath) else None

a = Analysis(
    [os.path.join("src", "roam.py")],
    pathex=["src", os.path.join("src", "entity")],
    binaries=[],
    datas=[
        ("assets", "assets"),
        ("schemas", "schemas"),
        ("config.yml", "."),
        (os.path.join("src", "media"), os.path.join("src", "media")),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Roam",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    icon=icon,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="Roam",
)
