import os

os.environ["SDL_VIDEODRIVER"] = "dummy"
os.environ["SDL_AUDIODRIVER"] = "dummy"
import json
import pygame
import pytest
from unittest.mock import MagicMock, patch

from world.room import Room


@pytest.fixture(scope="module", autouse=True)
def init_pygame():
    pygame.init()
    yield
    pygame.quit()


def createWorldScreen():
    from config.config import Config
    from screen.worldScreen import WorldScreen

    config = Config()
    gameDisplay = pygame.display.set_mode((800, 600))
    graphik = MagicMock()
    graphik.getGameDisplay.return_value = gameDisplay
    status = MagicMock()
    stats = MagicMock()
    stats.incrementRoomsExplored = MagicMock()
    stats.incrementScore = MagicMock()
    player = MagicMock()
    ws = WorldScreen.__new__(WorldScreen)
    ws.config = config
    ws.graphik = graphik
    ws.status = status
    ws.stats = stats
    ws.player = player
    ws.visitedRooms = set()
    ws.roomPreloader = MagicMock()
    return ws


def createMockRoom(gridSize, x=0, y=0):
    graphik = MagicMock()
    room = Room("test", gridSize, (0, 0, 0), x, y, graphik)
    return room


def test_changeRooms_increments_roomsExplored_for_new_room():
    """When the room does not exist in the map and must be generated,
    entering it should still increment roomsExplored."""
    ws = createWorldScreen()
    gridSize = ws.config.gridSize

    currentRoom = createMockRoom(gridSize, 0, 0)
    ws.currentRoom = currentRoom
    ws.visitedRooms.add((0, 0))

    # player is at top edge facing up -> new room at (0, -1)
    ws.player.getDirection.return_value = 0
    loc = currentRoom.getGrid().getLocationByCoordinates(0, 0)
    currentRoom.addEntity(ws.player)
    currentRoom.addEntityToLocation(ws.player, loc)

    newRoom = createMockRoom(gridSize, 0, -1)
    ws.map = MagicMock()
    ws.map.getRoom.return_value = -1
    ws.map.generateNewRoom.return_value = newRoom
    ws.map.getLocationOfEntity.return_value = loc

    with patch("os.path.exists", return_value=False):
        ws.changeRooms()

    ws.map.generateNewRoom.assert_called_once()
    ws.stats.incrementRoomsExplored.assert_called_once()


def test_changeRooms_does_not_increment_roomsExplored_for_visited_room():
    ws = createWorldScreen()
    gridSize = ws.config.gridSize

    currentRoom = createMockRoom(gridSize, 0, 0)
    ws.currentRoom = currentRoom
    ws.visitedRooms.add((0, 0))
    ws.visitedRooms.add((0, -1))

    # player is at top edge facing up -> room at (0, -1) already visited
    ws.player.getDirection.return_value = 0
    loc = currentRoom.getGrid().getLocationByCoordinates(0, 0)
    currentRoom.addEntity(ws.player)
    currentRoom.addEntityToLocation(ws.player, loc)

    existingRoom = createMockRoom(gridSize, 0, -1)
    ws.map = MagicMock()
    ws.map.getRoom.return_value = existingRoom
    ws.map.getLocationOfEntity.return_value = loc

    with patch("os.path.exists", return_value=False):
        ws.changeRooms()

    ws.stats.incrementRoomsExplored.assert_not_called()


def test_changeRooms_increments_for_pregenerated_but_unvisited_room():
    """When a room was pre-generated (e.g. by rendering) but never visited
    by the player, entering it should still increment roomsExplored."""
    ws = createWorldScreen()
    gridSize = ws.config.gridSize

    currentRoom = createMockRoom(gridSize, 0, 0)
    ws.currentRoom = currentRoom
    ws.visitedRooms.add((0, 0))

    # player is at top edge facing up -> room at (0, -1) exists but not visited
    ws.player.getDirection.return_value = 0
    loc = currentRoom.getGrid().getLocationByCoordinates(0, 0)
    currentRoom.addEntity(ws.player)
    currentRoom.addEntityToLocation(ws.player, loc)

    # room already exists in the map (pre-generated by rendering)
    pregeneratedRoom = createMockRoom(gridSize, 0, -1)
    ws.map = MagicMock()
    ws.map.getRoom.return_value = pregeneratedRoom
    ws.map.getLocationOfEntity.return_value = loc

    with patch("os.path.exists", return_value=False):
        ws.changeRooms()

    # should still increment because the player hasn't visited (0, -1) yet
    ws.stats.incrementRoomsExplored.assert_called_once()
    assert (0, -1) in ws.visitedRooms


def test_saveVisitedRoomsToFile(tmp_path):
    ws = createWorldScreen()
    ws.config.pathToSaveDirectory = str(tmp_path)
    ws.visitedRooms = {(0, 0), (1, 0), (0, -1)}

    ws.saveVisitedRoomsToFile()

    path = tmp_path / "visitedRooms.json"
    assert path.exists()
    data = json.loads(path.read_text())
    loaded = {(r["x"], r["y"]) for r in data["rooms"]}
    assert loaded == {(0, 0), (1, 0), (0, -1)}


def test_loadVisitedRoomsFromFile(tmp_path):
    ws = createWorldScreen()
    ws.config.pathToSaveDirectory = str(tmp_path)

    data = {"rooms": [{"x": 0, "y": 0}, {"x": 2, "y": 3}, {"x": -1, "y": 5}]}
    (tmp_path / "visitedRooms.json").write_text(json.dumps(data))

    ws.loadVisitedRoomsFromFile()

    assert ws.visitedRooms == {(0, 0), (2, 3), (-1, 5)}


def test_visitedRooms_persisted_prevents_double_counting(tmp_path):
    """After save/load, revisiting a room should not increment the stat."""
    ws = createWorldScreen()
    ws.config.pathToSaveDirectory = str(tmp_path)
    gridSize = ws.config.gridSize

    # simulate having visited (0, 0) and (0, -1) in a prior session
    ws.visitedRooms = {(0, 0), (0, -1)}
    ws.saveVisitedRoomsToFile()

    # new session: load visited rooms
    ws2 = createWorldScreen()
    ws2.config.pathToSaveDirectory = str(tmp_path)
    ws2.loadVisitedRoomsFromFile()

    currentRoom = createMockRoom(gridSize, 0, 0)
    ws2.currentRoom = currentRoom
    ws2.player.getDirection.return_value = 0
    loc = currentRoom.getGrid().getLocationByCoordinates(0, 0)
    currentRoom.addEntity(ws2.player)
    currentRoom.addEntityToLocation(ws2.player, loc)

    existingRoom = createMockRoom(gridSize, 0, -1)
    ws2.map = MagicMock()
    ws2.map.getRoom.return_value = existingRoom
    ws2.map.getLocationOfEntity.return_value = loc

    with patch("os.path.exists", return_value=False):
        ws2.changeRooms()

    ws2.stats.incrementRoomsExplored.assert_not_called()


def test_migrateVisitedRoomsFromRoomFiles(tmp_path):
    """Legacy saves without visitedRooms.json should seed from room files."""
    ws = createWorldScreen()
    ws.config.pathToSaveDirectory = str(tmp_path)

    rooms_dir = tmp_path / "rooms"
    rooms_dir.mkdir()
    (rooms_dir / "room_0_0.json").write_text("{}")
    (rooms_dir / "room_1_0.json").write_text("{}")
    (rooms_dir / "room_-2_3.json").write_text("{}")
    (rooms_dir / "not_a_room.txt").write_text("{}")

    ws._migrateVisitedRoomsFromRoomFiles()

    assert ws.visitedRooms == {(0, 0), (1, 0), (-2, 3)}
    assert ws._visitedRoomsDirty is True


def test_save_skips_visitedRooms_when_not_dirty(tmp_path):
    """When visitedRooms hasn't changed, saveSynchronous() should not write it."""
    ws = createWorldScreen()
    ws.config.pathToSaveDirectory = str(tmp_path)
    ws.config.showMiniMap = False
    ws.visitedRooms = {(0, 0)}
    ws._visitedRoomsDirty = False
    ws.currentRoom = MagicMock()
    ws.roomJsonReaderWriter = MagicMock()
    ws.tickCounter = MagicMock()
    ws._saveExecutor = MagicMock()
    ws._saveLock = MagicMock()
    ws.saveCurrentRoomToFile = MagicMock()
    ws.savePlayerLocationToFile = MagicMock()
    ws.savePlayerAttributesToFile = MagicMock()
    ws.savePlayerInventoryToFile = MagicMock()

    ws.saveSynchronous()

    assert not (tmp_path / "visitedRooms.json").exists()
