import os

os.environ["SDL_VIDEODRIVER"] = "dummy"
os.environ["SDL_AUDIODRIVER"] = "dummy"
import pygame
import pytest
from unittest.mock import MagicMock, patch

from world.room import Room


@pytest.fixture(scope="module", autouse=True)
def init_pygame():
    pygame.init()
    yield
    pygame.quit()


def createWorldScreen():
    from config.config import Config
    from screen.worldScreen import WorldScreen

    config = Config()
    gameDisplay = pygame.display.set_mode((800, 600))
    graphik = MagicMock()
    graphik.getGameDisplay.return_value = gameDisplay
    status = MagicMock()
    stats = MagicMock()
    stats.incrementRoomsExplored = MagicMock()
    stats.incrementScore = MagicMock()
    player = MagicMock()
    ws = WorldScreen.__new__(WorldScreen)
    ws.config = config
    ws.graphik = graphik
    ws.status = status
    ws.stats = stats
    ws.player = player
    ws.visitedRooms = set()
    return ws


def createMockRoom(gridSize, x=0, y=0):
    graphik = MagicMock()
    room = Room("test", gridSize, (0, 0, 0), x, y, graphik)
    return room


def test_changeRooms_increments_roomsExplored_for_new_room():
    ws = createWorldScreen()
    gridSize = ws.config.gridSize

    currentRoom = createMockRoom(gridSize, 0, 0)
    ws.currentRoom = currentRoom
    ws.visitedRooms.add((0, 0))

    # player is at top edge facing up -> new room at (0, -1)
    ws.player.getDirection.return_value = 0
    loc = currentRoom.getGrid().getLocationByCoordinates(0, 0)
    currentRoom.addEntity(ws.player)
    currentRoom.addEntityToLocation(ws.player, loc)

    newRoom = createMockRoom(gridSize, 0, -1)
    ws.map = MagicMock()
    ws.map.getRoom.return_value = newRoom
    ws.map.getLocationOfEntity.return_value = loc

    with patch("os.path.exists", return_value=False):
        ws.changeRooms()

    ws.stats.incrementRoomsExplored.assert_called_once()


def test_changeRooms_does_not_increment_roomsExplored_for_visited_room():
    ws = createWorldScreen()
    gridSize = ws.config.gridSize

    currentRoom = createMockRoom(gridSize, 0, 0)
    ws.currentRoom = currentRoom
    ws.visitedRooms.add((0, 0))
    ws.visitedRooms.add((0, -1))

    # player is at top edge facing up -> room at (0, -1) already visited
    ws.player.getDirection.return_value = 0
    loc = currentRoom.getGrid().getLocationByCoordinates(0, 0)
    currentRoom.addEntity(ws.player)
    currentRoom.addEntityToLocation(ws.player, loc)

    existingRoom = createMockRoom(gridSize, 0, -1)
    ws.map = MagicMock()
    ws.map.getRoom.return_value = existingRoom
    ws.map.getLocationOfEntity.return_value = loc

    with patch("os.path.exists", return_value=False):
        ws.changeRooms()

    ws.stats.incrementRoomsExplored.assert_not_called()


def test_changeRooms_increments_for_pregenerated_but_unvisited_room():
    """When a room was pre-generated (e.g. by rendering) but never visited
    by the player, entering it should still increment roomsExplored."""
    ws = createWorldScreen()
    gridSize = ws.config.gridSize

    currentRoom = createMockRoom(gridSize, 0, 0)
    ws.currentRoom = currentRoom
    ws.visitedRooms.add((0, 0))

    # player is at top edge facing up -> room at (0, -1) exists but not visited
    ws.player.getDirection.return_value = 0
    loc = currentRoom.getGrid().getLocationByCoordinates(0, 0)
    currentRoom.addEntity(ws.player)
    currentRoom.addEntityToLocation(ws.player, loc)

    # room already exists in the map (pre-generated by rendering)
    pregeneratedRoom = createMockRoom(gridSize, 0, -1)
    ws.map = MagicMock()
    ws.map.getRoom.return_value = pregeneratedRoom
    ws.map.getLocationOfEntity.return_value = loc

    with patch("os.path.exists", return_value=False):
        ws.changeRooms()

    # should still increment because the player hasn't visited (0, -1) yet
    ws.stats.incrementRoomsExplored.assert_called_once()
    assert (0, -1) in ws.visitedRooms
