from unittest.mock import MagicMock

from src.world.map import Map
from src.world.roomPreloader import RoomPreloader


def _createDependencies(tmp_path):
    graphik = MagicMock()
    tickCounter = MagicMock()
    tickCounter.getTick.return_value = 0
    config = MagicMock()
    config.pathToSaveDirectory = str(tmp_path)
    config.worldBorder = 0
    config.gridSize = 3
    return graphik, tickCounter, config


def _createPreloaderAndMap(tmp_path):
    graphik, tickCounter, config = _createDependencies(tmp_path)
    preloader = RoomPreloader(3, graphik, tickCounter, config)
    gameMap = Map(3, graphik, tickCounter, config)
    return preloader, gameMap


def test_initialization(tmp_path):
    graphik, tickCounter, config = _createDependencies(tmp_path)
    preloader = RoomPreloader(3, graphik, tickCounter, config)

    assert preloader.gridSize == 3
    assert preloader._pending == set()


def test_preload_generates_adjacent_rooms(tmp_path):
    preloader, gameMap = _createPreloaderAndMap(tmp_path)

    # Start with a room at (0, 0)
    gameMap.generateNewRoom(0, 0)

    # Preload nearby rooms
    preloader.preloadNearbyRooms(0, 0, gameMap)

    # Wait for background tasks to complete
    preloader.shutdown(wait=True)

    # All four adjacent rooms should now be loaded
    assert gameMap.hasRoom(0, -1)
    assert gameMap.hasRoom(0, 1)
    assert gameMap.hasRoom(-1, 0)
    assert gameMap.hasRoom(1, 0)


def test_preload_skips_already_loaded_rooms(tmp_path):
    preloader, gameMap = _createPreloaderAndMap(tmp_path)

    # Pre-generate room at (1, 0)
    existingRoom = gameMap.generateNewRoom(1, 0)
    initialRoomCount = len(gameMap.getRooms())

    # Preload from (0, 0) — (1, 0) already exists
    preloader.preloadNearbyRooms(0, 0, gameMap)
    preloader.shutdown(wait=True)

    # (1, 0) should still be the original room object
    assert gameMap.getRoom(1, 0) == existingRoom

    # Other three rooms generated + original = 4 + original(1,0) = 5
    # (0,0) was NOT generated by the preloader since it's the current room
    assert len(gameMap.getRooms()) == initialRoomCount + 3


def test_preload_respects_world_border(tmp_path):
    graphik, tickCounter, config = _createDependencies(tmp_path)
    config.worldBorder = 1  # border at 1 means rooms at abs(x/y) > 1 are blocked

    preloader = RoomPreloader(3, graphik, tickCounter, config)
    gameMap = Map(3, graphik, tickCounter, config)

    # Player at (1, 1) — all neighbors are at abs >= 2, which exceeds border
    preloader.preloadNearbyRooms(1, 1, gameMap)
    preloader.shutdown(wait=True)

    # Only (0, 1) and (1, 0) are within border, (2, 1) and (1, 2) are outside
    assert gameMap.hasRoom(0, 1)
    assert gameMap.hasRoom(1, 0)
    assert not gameMap.hasRoom(2, 1)
    assert not gameMap.hasRoom(1, 2)


def test_preload_does_not_duplicate_pending_work(tmp_path):
    preloader, gameMap = _createPreloaderAndMap(tmp_path)

    # Call preload twice in quick succession for the same position
    preloader.preloadNearbyRooms(0, 0, gameMap)
    preloader.preloadNearbyRooms(0, 0, gameMap)

    preloader.shutdown(wait=True)

    # Should still have exactly 4 rooms, no duplicates
    assert len(gameMap.getRooms()) == 4


def test_shutdown(tmp_path):
    preloader, gameMap = _createPreloaderAndMap(tmp_path)

    preloader.shutdown(wait=True)
    # Should not raise


def test_has_room_on_map(tmp_path):
    _, gameMap = _createPreloaderAndMap(tmp_path)

    assert not gameMap.hasRoom(0, 0)
    gameMap.generateNewRoom(0, 0)
    assert gameMap.hasRoom(0, 0)
